CREATE SCHEMA IF NOT EXISTS GroceryStore;
USE GroceryStore;

CREATE TABLE IF NOT EXISTS Department (
  id INT NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Product (
  productID INT NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  departmentID INT NOT NULL,
  imgLink VARCHAR(255) NOT NULL
);
  

CREATE TABLE IF NOT EXISTS ShoppingCart (
  id INT NOT NULL PRIMARY KEY,
  productID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Account (
  username VARCHAR(20) NOT NULL PRIMARY KEY,
  password VARCHAR(20) NOT NULL,
  cartID INT NOT NULL,
  creditCard INT NOT NULL,
  email VARCHAR(45) NOT NULL
);
