USE GroceryStore;

INSERT INTO Department VALUES
(1, 'Fruits');
(2, 'Vegetables');
(3, 'Meat');
(4, 'Seafood');
(5, 'Dairy and Eggs');

INSERT INTO Product VALUES
(1, 'Apple', 0.50, 1, "images/apple.jpg");
(2, 'Banana', 0.35, 1, "images/banana.jpg");
(3, 'Avacado', 1.25, 1, "images/avocado.jpg");
(4, 'Grapefruit', 1.29, 1, "images/grapefruit.jpg");
(5, 'Limes', 0.50, 1, "images/limes.jpg");
(6, 'Plums', 0.50, 1, "images/plums.jps");
(7, 'Bag of Grapes', 5.38, 1), "images/bag-of-grapes.jpeg";
(8, 'Bag of Lemons', 3.99, 1, "images/bag-of-lemons.jpeg");
(9, 'Bag of Oranges', 3.99, 1, "images/bag-of-oranges.jpeg");
(10, 'Lemons', 0.79, 1, "images/lemons.png");
(11, 'Lettuce - Red Leaf', 1.79, 2, "images/lettuce-red-leaf.png");
(12, 'Lettuce - Green Leaf', 2.29, 2, "images/lettuce-green-leaf.png");
(13, 'Corn on the Cob', 0.40, 2, "images/corn-on-the-cob.jpeg");
(14, 'Sweet Onions', 0.50, 2, "images/sweet-onion.jpeg");
(15, 'Red Bell Pepper', 0.99, 2, "images/red-bell-pepper.jpg");
(16, 'Yellow Bell Pepper', 0.99, 2, "images/yellow-bell-pepper.jpg");
(17, 'Tomatoes', 1.00, 2, "images/tomatoes.jpeg");
(18, 'Cucumber', 0.59, 2, "images/cucumber.jpg");
(19, 'Broccoli', 0.88, 2, "images/broccoli.jpg");
(20, 'Bag of Baby Carrots', 1.99, 2, "images/bag-of-baby-carrots.png");
(21, 'lb of Ground Beef', 3.99, 3, "images/ground-beef.jpeg");
(22, 'Boneless Ribeye Steak', 9.80, 3, "images/boneless-ribeye-steak.jpeg");
(23, 'Sirloin Steak', 11.11, 3, "images/sirloin-steak.jpg");
(24, 'Tenderloin Steak', 12.00, 3, "images/tenderloin-steak.jpeg");
(25, 'Chuck Roast', 18.74, 3, "images/chuck-roast.jpeg");
(26, 'Chuck Steak', 9.60, 3, "images/chuck-steak.jpeg");
(27, 'Back Ribs', 17.57, 3, "images/back-ribs.jpg");
(28, 'T-Bone Steak', 11.48, 3, "images/t-bone-steak.jpg");
(29, 'Bottom Round Roast', 16.12, 3, "images/bottom-round-roast");
(30, 'Pork Chops', 10.77, 3, "images/pork-chops");
(31, 'Tilapia', 5.99, 4, "images/tilapia.jpg");
(32, 'Salmon', 6.99, 4, "images/salmon");
(33, 'Skinless Flounder Fillets', 4.49, 4, "images/skinless-flounder-fillets.jpg");
(34, 'Skinless Mahi Mahi', 6.99, 4, "images/skinless-mahi-mahi.jpg");
(35, 'Catfish Fillet', 6.99, 4, "images/catfish-fillet.jpeg");
(36, 'Tuna Steak', 6.40, 4, "images/tuna-steak.jpg");
(37, 'Jumbo Raw Shrimp', 8.99, 4, "images/jumbo-raw-shrimp.jpg");
(38, 'Popcorn Shrimp', 5.99, 4, "images/popcorn-shrimp.jpg");
(39, 'Butterfly Shrimp', 3.99, 4, "images/butterfly-shrimp.png");
(40, 'Crab Meat', 19.99, 4, "images/crab-meat.jpg");
(41, 'Greek Yogurt', 3.79, 5, "images/greek-yogurt.jpeg");
(42, 'Coffee Creamer', 1.79, 5, "images/coffee-creamer.png");
(43, 'Coconut Milk', 2.08, 5, "images/coconut-milk.jpeg");
(44, 'Colby Cheese Bar', 6.99, 5, "images/colby-cheese-bar.jpg");
(45, 'Mild Cheddar Cheese Bar', 6.99, 5, "images/mild-cheddar-cheese-bar.jpeg");
(46, 'Sharp Cheddar Cheese Bar', 6.99, 5, "images/sharp-cheddar-cheese-bar.jpeg");
(47, 'Whole Milk', 2.49, 5, "images/whole-milk.jpeg");
(48, '1% Lowfat Milk', 2.49, 5, "images/1%-lowfat-milk.jpeg");
(49, 'Fat Free Skim Milk', 1.79, 5, "images/fat-free-skim-milk.jpeg");
(50, 'Monterey Jack Cheese', 3.99, 5, "images/monterey-jack-cheese.jpg");